import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { signIn } from '@/services/auth';
import { colors, radius, spacing } from '@/theme';
import { PrimaryButton, SoftButton } from '@/components/ui';

export default function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const submit = async () => { if (!email.includes('@') || password.length < 4) { setError('A valid email and a few password characters are enough to start.'); return; } try { await signIn(email, password); } catch (e) { setError(e instanceof Error ? e.message : 'Something gentle went wrong.'); return; } router.replace('/onboarding'); };
  return <ScrollView style={styles.root} contentContainerStyle={styles.content}><Text style={styles.icon}>💛</Text><Text style={styles.title}>Welcome, mama.</Text><Text style={styles.subtitle}>We've been waiting for you. This little space is yours.</Text><View style={styles.card}><Text style={styles.label}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor="#9B909F" style={styles.input} /><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Your secret little key" placeholderTextColor="#9B909F" style={styles.input} />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton title="Continue with care →" onPress={submit} /><Pressable onPress={() => setError('Password reset is ready for the Supabase auth connection.')}><Text style={styles.link}>Forgot password?</Text></Pressable><Text style={styles.or}>or</Text><SoftButton title="Continue with Google" onPress={() => setError('Google sign-in needs your Supabase OAuth provider enabled.')} /></View><Pressable onPress={() => router.push('/signup')}><Text style={styles.signup}>New here? <Text style={{ fontWeight: '900' }}>Create your space</Text></Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, content: { padding: 24, paddingTop: 65, maxWidth: 600, width: '100%', alignSelf: 'center' }, icon: { fontSize: 36 }, title: { fontSize: 32, fontWeight: '900', color: colors.text, marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: 8 }, card: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, marginTop: 26 }, label: { color: colors.text, fontWeight: '800', marginBottom: 7, marginTop: 10 }, input: { minHeight: 52, borderRadius: radius.md, backgroundColor: colors.background, paddingHorizontal: 16, color: colors.text, fontSize: 16 }, error: { color: '#705B45', backgroundColor: colors.butterYellow, padding: 10, borderRadius: 12, marginVertical: 12 }, link: { color: colors.text, textAlign: 'center', marginVertical: 15, fontWeight: '800' }, or: { textAlign: 'center', color: colors.muted, marginBottom: 10 }, signup: { textAlign: 'center', color: colors.text, marginTop: 22, fontSize: 15 } });
