import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { updateUser } from '@/services/auth';
import { colors, radius, spacing } from '@/theme';
import { PrimaryButton } from '@/components/ui';

export default function Onboarding(){const[name,setName]=useState('');const[baby,setBaby]=useState('');const[age,setAge]=useState('');return <ScrollView style={styles.root} contentContainerStyle={styles.content}><Text style={styles.step}>A tiny introduction · 1 minute</Text><Text style={styles.title}>Let's make this feel like yours. ♡</Text><Text style={styles.sub}>You can skip anything. Nothing here is a test.</Text><View style={styles.card}><Text style={styles.label}>Your name</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Mama" placeholderTextColor="#9B909F"/><Text style={styles.label}>Baby's name</Text><TextInput style={styles.input} value={baby} onChangeText={setBaby} placeholder="Little one" placeholderTextColor="#9B909F"/><Text style={styles.label}>Baby's age</Text><TextInput style={styles.input} value={age} onChangeText={setAge} placeholder="e.g. 3 weeks" placeholderTextColor="#9B909F"/><Text style={styles.note}>Your answers personalize the experience and stay minimal.</Text><PrimaryButton title="Take me home →" onPress={async()=>{await updateUser({name:name||'Mama',babyName:baby||'Little One',babyAge:age||'Newborn'});router.replace('/mother-dashboard')}}/></View></ScrollView>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},content:{padding:24,paddingTop:65,maxWidth:600,width:'100%',alignSelf:'center'},step:{fontWeight:'800',color:colors.muted},title:{fontSize:31,fontWeight:'900',color:colors.text,marginTop:12},sub:{color:colors.muted,lineHeight:23,marginTop:8},card:{backgroundColor:colors.white,borderRadius:radius.lg,padding:spacing.lg,marginTop:25},label:{fontWeight:'800',color:colors.text,marginBottom:7,marginTop:10},input:{minHeight:52,borderRadius:radius.md,backgroundColor:colors.background,paddingHorizontal:16,color:colors.text,fontSize:16},note:{color:colors.muted,fontSize:13,lineHeight:19,marginVertical:15}});
