import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { signUp } from '@/services/auth';
import { colors, radius, spacing } from '@/theme';
import { PrimaryButton } from '@/components/ui';

export default function Signup() { const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const submit=async()=>{if(!name.trim()||!email.includes('@')||password.length<4){setError('Tell me your name, a valid email, and a short password.');return;} try { await signUp(email,password,name.trim()); } catch (e) { setError(e instanceof Error ? e.message : 'Something gentle went wrong.'); return; } router.replace('/onboarding');}; return <ScrollView style={styles.root} contentContainerStyle={styles.content}><Text style={styles.title}>A little space, just for you 🌷</Text><Text style={styles.sub}>We will keep the beginning simple. You can change anything later.</Text><View style={styles.card}><Text style={styles.label}>Your name</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="What should we call you?" placeholderTextColor="#9B909F"/><Text style={styles.label}>Email</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor="#9B909F"/><Text style={styles.label}>Password</Text><TextInput style={styles.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="Something only you know" placeholderTextColor="#9B909F"/>{error?<Text style={styles.error}>{error}</Text>:null}<PrimaryButton title="Create my MamaMind →" onPress={submit}/></View></ScrollView> }
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},content:{padding:24,paddingTop:70,maxWidth:600,width:'100%',alignSelf:'center'},title:{fontSize:31,fontWeight:'900',color:colors.text},sub:{color:colors.muted,lineHeight:23,marginTop:8},card:{backgroundColor:colors.white,borderRadius:radius.lg,padding:spacing.lg,marginTop:25},label:{fontWeight:'800',color:colors.text,marginBottom:7,marginTop:10},input:{minHeight:52,borderRadius:radius.md,backgroundColor:colors.background,paddingHorizontal:16,color:colors.text,fontSize:16},error:{backgroundColor:colors.butterYellow,color:colors.text,padding:10,borderRadius:12,marginVertical:12}});
